/* LOG4KMW_LOGGERS.CPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/



#include "log4kmw_records.hpp"
#include "log4kmw_loggers.hpp"

 log4kmw_loggers::logger_abc_t log4kmw_loggers::logger_abc;
std::mutex log4kmw_loggers::logger_mutex_abc;
 void log4kmw_loggers::log_event(log4kmw_events::BenuzerEingabe const & ev, log4kmw_loggers::logger_abc_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'abc' invalid (not initialized?)");
 log4kmw_records::abc rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_abc);
  log.logger().append(rec.record());
 }
}

 void log4kmw_loggers::log_event(log4kmw_events::MonitorAn const & ev, log4kmw_loggers::logger_abc_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'abc' invalid (not initialized?)");
 log4kmw_records::abc rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_abc);
  log.logger().append(rec.record());
 }
}

 void log4kmw_loggers::log_event(log4kmw_events::MonitorAus const & ev, log4kmw_loggers::logger_abc_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'abc' invalid (not initialized?)");
 log4kmw_records::abc rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_abc);
  log.logger().append(rec.record());
 }
}

 void log4kmw_loggers::log_event(log4kmw_events::NullstellungLenkwinkel const & ev, log4kmw_loggers::logger_abc_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'abc' invalid (not initialized?)");
 log4kmw_records::abc rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_abc);
  log.logger().append(rec.record());
 }
}

 void log4kmw_loggers::log_event(log4kmw_events::ResetBetriebsstundenGasfilter const & ev, log4kmw_loggers::logger_abc_t & log)
{
 if(!log.logger()) throw std::runtime_error("Logger 'abc' invalid (not initialized?)");
 log4kmw_records::abc rec;
 log4kmw_records::make_record_from_states(rec);
 {
  std::unique_lock<std::mutex> lock(log4kmw_loggers::logger_mutex_abc);
  log.logger().append(rec.record());
 }
}

