/* LOG4KMW_LOGGERS.HPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_LOGGERS_HPP_INC
#define LOG4KMW_LOGGERS_HPP_INC

#include "log4kmw_state.hpp"
#include "log4kmw_states.hpp"
#include "log4kmw_events.hpp"
#include "log4kmw_record.hpp"
#include "log4kmw_logger.hpp"
#include "log4kmw_events.hpp"
#include<string>
#include <thread>
#include <mutex>

namespace log4kmw_loggers{
 struct logger_abc_t{log4kmw::Logger<log4kmw_records::abc_t, log4kmw::persistence::memory_mapped_file>log;
 log4kmw::Logger<log4kmw_records::abc_t, log4kmw::persistence::memory_mapped_file>& logger(){return log;}};
 extern logger_abc_t logger_abc;
 extern std::mutex logger_mutex_abc;


 void log_event(log4kmw_events::BenuzerEingabe const &, logger_abc_t &);
 void log_event(log4kmw_events::MonitorAn const &, logger_abc_t &);
 void log_event(log4kmw_events::MonitorAus const &, logger_abc_t &);
 void log_event(log4kmw_events::NullstellungLenkwinkel const &, logger_abc_t &);
 void log_event(log4kmw_events::ResetBetriebsstundenGasfilter const &, logger_abc_t &);
}//namespace log4kmw_loggers
#endif
