/* LOG4KMW_LOGGERS_TESTS.CPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/



#include <iostream>
#include <type_traits>
#include <tuple>
#include <cstdint>
#include <memory>
#include <iterator>
#include <limits>
#include <cstdlib>
#include <time.h>
#include <sstream>
#include <vector>
#include <thread>
#include <chrono>
#include <random>
#include "log4kmw_states.hpp"
#include "log4kmw_records.hpp"
#include "log4kmw_loggers.hpp"

#ifdef _WIN32
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#else
#endif

#include "ceps_all.hh"

/*Start section "Log Printers"*/
namespace log4kmw_test{ namespace meta_info{
 enum base_type{Float,Double,Int,String};
 using state_name=std::string;using value_types_with_units=std::vector<base_type,int/*ceps::ast::Unit_rep*/>;
 std::vector< std::pair<std::string,std::vector<std::pair<base_type,ceps::ast::Unit_rep>>>>abc()
 {
  return   {
    std::make_pair(std::string("a_string"),std::vector<std::pair<base_type,ceps::ast::Unit_rep>>    {
     std::make_pair(base_type::String,0,0,0,0,0,0,0)    }
    )
  };
 }
 void log_print( log4kmw_loggers::logger_abc_t& logger) {
  for (auto it = logger.logger().cbegin(); it != logger.logger().cend();++it)
  {
  }
 }
}}/*End section "Log Printers"*/
void test_1(){
 log4kmw_loggers::logger_abc.logger().init(log4kmw::persistence::memory_mapped_file("test.bin", 2048, true));
 {
  log4kmw_states::write_state_CGW_FzGeschwindigkeit(log4kmw::State<SI::Quantity<SI::Unit<1,0,-1,0,0,0,0> ,double> >(5.555556));
  log4kmw_loggers::log_event(log4kmw_events::NullstellungLenkwinkel(), log4kmw_loggers::logger_abc);
  log4kmw_states::write_state_CGW_FzGeschwindigkeit(log4kmw::State<SI::Quantity<SI::Unit<1,0,-1,0,0,0,0> ,double> >(8.333333));
  log4kmw_loggers::log_event(log4kmw_events::MonitorAn(), log4kmw_loggers::logger_abc);
 }
}
void run_all_tests(){
 test_1();
}
