/* LOG4KMW_RECORDS.HPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_RECORDS_HPP_INC
#define LOG4KMW_RECORDS_HPP_INC

#include "log4kmw_state.hpp"
#include "log4kmw_states.hpp"
#include "log4kmw_events.hpp"
#include "log4kmw_record.hpp"
#include<string>

namespace log4kmw_records{
 using abc_t = log4kmw::State_record <
   log4kmw_states::a_string_t
 >;
struct abc{abc_t rec;abc_t& record(){return rec;} };

 void make_record_from_states(abc& rec);

}
#endif
