/* LOG4KMW_EVENTS.HPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


/* LOG4KMW_EVENTS.CPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_EVENTS_HPP_INC
#define LOG4KMW_EVENTS_HPP_INC

#include "log4kmw_event.hpp"


namespace log4kmw_events{
 typedef log4kmw::Event<4> BenuzerEingabe;
 typedef log4kmw::Event<2> MonitorAn;
 typedef log4kmw::Event<3> MonitorAus;
 typedef log4kmw::Event<0> NullstellungLenkwinkel;
 typedef log4kmw::Event<1> ResetBetriebsstundenGasfilter;
}

#endif
