/* LOG4KMW_RECORDS.CPP 
   CREATED Tue Apr 12 18:23:14 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (Mar 29 2016) BUILT WITH GCC 4.9.0 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/



#include "log4kmw_records.hpp"

void log4kmw_records::make_record_from_states(abc& rec)
{
 std::unique_lock<std::mutex> lock(log4kmw_states::global_lock);
 rec.record() = log4kmw_records::abc_t(
   log4kmw_states::read_state_a_string_no_lock()
 );
}
