/* LOG4KMW_STATES.HPP 
   CREATED Tue May 17 19:59:09 2016

   GENERATED BY logspec2cpp VERSION 0.4 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   BASED ON CEPS VERSION 1.1 (May 17 2016) BUILT WITH GCC 5.2.1 20151010 on GNU/LINUX 64BIT (C) BY THE AUTHORS OF ceps (ceps is hosted at github: https://github.com/cepsdev/ceps.git) 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_STATES_HPP_INC
#define LOG4KMW_STATES_HPP_INC

#include "log4kmw_state.hpp"
#include<string>
#include<thread>
#include<mutex>

namespace log4kmw_states{
 extern std::mutex global_lock;
 extern log4kmw::State<int> Current_event;
 extern log4kmw::State<int> Current_states;
 extern log4kmw::State<int> Synch_counter;

 typedef log4kmw::State<int> Current_event_t;
 typedef log4kmw::State<int> Current_states_t;
 typedef log4kmw::State<int> Synch_counter_t;

 void write_state_Current_event(Current_event_t const &);
 Current_event_t   read_state_Current_event(); 
 Current_event_t   read_state_Current_event_no_lock(); 
 void write_state_Current_states(Current_states_t const &);
 Current_states_t   read_state_Current_states(); 
 Current_states_t   read_state_Current_states_no_lock(); 
 void write_state_Synch_counter(Synch_counter_t const &);
 Synch_counter_t   read_state_Synch_counter(); 
 Synch_counter_t   read_state_Synch_counter_no_lock(); 
}

#endif
