/* LOG4KMW_RECORDS.CPP 
   CREATED Tue Mar 29 10:36:29 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/



#include "log4kmw_records.hpp"

void log4kmw_records::make_record_from_states(abc& rec)
{
 std::unique_lock<std::mutex> lock(log4kmw_states::global_lock);
 rec = log4kmw_records::abc(
   log4kmw_states::read_state_a_string_no_lock()
 );
}
void log4kmw_records::make_record_from_states(def& rec)
{
 std::unique_lock<std::mutex> lock(log4kmw_states::global_lock);
 rec = log4kmw_records::def(
   log4kmw_states::read_state_a_string_no_lock()
 );
}
void log4kmw_records::make_record_from_states(status_all& rec)
{
 std::unique_lock<std::mutex> lock(log4kmw_states::global_lock);
 rec = log4kmw_records::status_all(
   log4kmw_states::read_state_Monitor_status_no_lock(),
   log4kmw_states::read_state_Textfeld_no_lock(),
   log4kmw_states::read_state_CGW_FzGeschwindigkeit_no_lock(),
   log4kmw_states::read_state_CMK_Gesamtkilometer_no_lock()
 );
}
void log4kmw_records::make_record_from_states(record2& rec)
{
 std::unique_lock<std::mutex> lock(log4kmw_states::global_lock);
 rec = log4kmw_records::record2(
   log4kmw_states::read_state_a_string_no_lock(),
   log4kmw_states::read_state_an_int_no_lock()
 );
}
