/* LOG4KMW_EVENTS.HPP 
   CREATED Tue Mar 29 10:36:29 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_EVENTS_HPP_INC
#define LOG4KMW_EVENTS_HPP_INC

#include "log4kmw_event.hpp"


namespace log4kmw_events{
 typedef log4kmw::Event<4> BenuzerEingabe;
 typedef log4kmw::Event<2> MonitorAn;
 typedef log4kmw::Event<3> MonitorAus;
 typedef log4kmw::Event<0> NullstellungLenkwinkel;
 typedef log4kmw::Event<1> ResetBetriebsstundenGasfilter;
}

#endif
