/* LOG4KMW_EVENTS.CPP 
   CREATED Tue Mar 29 10:36:29 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#include "log4kmw_events.hpp"


template<> const std::string log4kmw::Event<4>::description_ = "Texteingabe durch Benutzer.";
template<> const std::string log4kmw::Event<2>::description_ = "Monitor angeschaltet.";
template<> const std::string log4kmw::Event<3>::description_ = "Monitor ausgeschaltet.";
template<> const std::string log4kmw::Event<0>::description_ = "Nullstellung Leitwinkel.";
template<> const std::string log4kmw::Event<1>::description_ = "Reset des Betriebsstunden Gasfilters.";
