/* LOG4KMW_RECORDS.HPP 
   CREATED Tue Mar 29 10:36:29 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_RECORDS_HPP_INC
#define LOG4KMW_RECORDS_HPP_INC

#include "log4kmw_state.hpp"
#include "log4kmw_states.hpp"
#include "log4kmw_events.hpp"
#include "log4kmw_record.hpp"
#include<string>

namespace log4kmw_records{
 using abc = log4kmw::State_record <
   log4kmw_states::a_string_t
 >;

 void make_record_from_states(abc& rec);

 using def = log4kmw::State_record <
   log4kmw_states::a_string_t
 >;

 void make_record_from_states(def& rec);

 using status_all = log4kmw::State_record <
   log4kmw_states::Monitor_status_t,
   log4kmw_states::Textfeld_t,
   log4kmw_states::CGW_FzGeschwindigkeit_t,
   log4kmw_states::CMK_Gesamtkilometer_t
 >;

 void make_record_from_states(status_all& rec);

 using record2 = log4kmw::State_record <
   log4kmw_states::a_string_t,
   log4kmw_states::an_int_t
 >;

 void make_record_from_states(record2& rec);

}
#endif
