/* LOG4KMW_EVENTS.CPP 
   CREATED Wed Mar 23 11:06:51 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#include "log4kmw_events.hpp"


template<> const std::string log4kmw::Event<3>::description_ = "CAN 4: APU CU CommunicationStatus changed.";
template<> const std::string log4kmw::Event<4>::description_ = "APU CU Internal Error State changed.";
template<> const std::string log4kmw::Event<5>::description_ = "APU CU Selftest Error State changed.";
template<> const std::string log4kmw::Event<6>::description_ = "CAN 4: APU ECU CommunicationStatus changed.";
template<> const std::string log4kmw::Event<7>::description_ = "APU ECU Internal Error State changed.";
template<> const std::string log4kmw::Event<10>::description_ = "CAN 4: APU FAN Top CommunicationStatus changed.";
template<> const std::string log4kmw::Event<11>::description_ = "APU Fan Top Internal Error State changed.";
template<> const std::string log4kmw::Event<8>::description_ = "CAN 4: APU FAN Top CommunicationStatus changed.";
template<> const std::string log4kmw::Event<9>::description_ = "APU Fan Top Internal Error State changed.";
template<> const std::string log4kmw::Event<0>::description_ = "CAN 4: APU UC CommunicationStatus changed.";
template<> const std::string log4kmw::Event<1>::description_ = "APU UC Internal Error State changed.";
template<> const std::string log4kmw::Event<2>::description_ = "APU UC MonitoringStatus changed.";
template<> const std::string log4kmw::Event<23>::description_ = "FGR PPC gebootet.";
template<> const std::string log4kmw::Event<26>::description_ = "CAN 4: APU Lüfter1 Status changed.";
template<> const std::string log4kmw::Event<27>::description_ = "CAN 4: APU Lüfter2 Status changed.";
template<> const std::string log4kmw::Event<25>::description_ = "CAN 3: BAG 10 Status changed.";
template<> const std::string log4kmw::Event<16>::description_ = "FGR IO CAN Status changed";
template<> const std::string log4kmw::Event<17>::description_ = "FGR IO meldet internen Fehler";
template<> const std::string log4kmw::Event<18>::description_ = "FGR PPC CAN Status changed";
template<> const std::string log4kmw::Event<19>::description_ = "FGR PPC meldet internen Fehler";
template<> const std::string log4kmw::Event<14>::description_ = "FGR Powersupply CAN Status changed";
template<> const std::string log4kmw::Event<15>::description_ = "FGR Powersupply meldet internen Fehler";
template<> const std::string log4kmw::Event<12>::description_ = "FGR Videomatrix CAN Status changed";
template<> const std::string log4kmw::Event<13>::description_ = "FGR Videomatrix meldet internen Fehler";
template<> const std::string log4kmw::Event<28>::description_ = "IFIS AliveStatus changed.";
template<> const std::string log4kmw::Event<39>::description_ = "CAN2 / SerialBus: NAV CAN CommunicationStatus changed.";
template<> const std::string log4kmw::Event<40>::description_ = "NAV Status changed.";
template<> const std::string log4kmw::Event<37>::description_ = "CAN3: RFH CAN CommunicationStatus changed.";
template<> const std::string log4kmw::Event<38>::description_ = "RFH DoorStatus changed.";
template<> const std::string log4kmw::Event<36>::description_ = "RFH Videosignal Sync has changed.";
template<> const std::string log4kmw::Event<30>::description_ = "HS Stellung verändert (0 / 1 / 2)";
template<> const std::string log4kmw::Event<35>::description_ = "HTW gestartet / gestoppt.";
template<> const std::string log4kmw::Event<33>::description_ = "Rote Warnmeldung aufgetreten / behoben.";
template<> const std::string log4kmw::Event<34>::description_ = "Gelbe Warnmeldung aufgetreten / behoben.";
template<> const std::string log4kmw::Event<32>::description_ = "Überspannung Bordnetz Gesamtfahrzeug.";
template<> const std::string log4kmw::Event<31>::description_ = "Unterspannung Bordnetz Gesamtfahrzeug.";
template<> const std::string log4kmw::Event<24>::description_ = "CAN 1: ZLHV Status changed.";
template<> const std::string log4kmw::Event<22>::description_ = "Any ZM entry has changed.";
template<> const std::string log4kmw::Event<29>::description_ = "Benutzer hat in der ZM einen Fehler als behoben markiert";
template<> const std::string log4kmw::Event<20>::description_ = "ZWL Extern CAN Status changed";
template<> const std::string log4kmw::Event<21>::description_ = "ZWL Extern meldet internen Fehler";
