/* LOG4KMW_EVENTS.HPP 
   CREATED Wed Mar 23 11:06:51 2016

   GENERATED BY logspec2cpp VERSION 0.3 (c) Krauss-Maffei-Wegmann GmbH & Co. KG. 
   THIS IS A GENERATED FILE. DO NOT MODIFY.
*/


#ifndef LOG4KMW_EVENTS_HPP_INC
#define LOG4KMW_EVENTS_HPP_INC

#include "log4kmw_event.hpp"


namespace log4kmw_events{
 typedef log4kmw::Event<3> APU_CU_CommunicationChanged;
 typedef log4kmw::Event<4> APU_CU_InternalErrorChanged;
 typedef log4kmw::Event<5> APU_CU_SelftestErrorChanged;
 typedef log4kmw::Event<6> APU_ECU_CommunicationChanged;
 typedef log4kmw::Event<7> APU_ECU_InternalErrorChanged;
 typedef log4kmw::Event<10> APU_Fan_Bottom_CommunicationChanged;
 typedef log4kmw::Event<11> APU_Fan_Bottom_InternalErrorChanged;
 typedef log4kmw::Event<8> APU_Fan_Top_CommunicationChanged;
 typedef log4kmw::Event<9> APU_Fan_Top_InternalErrorChanged;
 typedef log4kmw::Event<0> APU_UC_CommunicationChanged;
 typedef log4kmw::Event<1> APU_UC_InternalErrorChanged;
 typedef log4kmw::Event<2> APU_UC_MonitoringStatusChanged;
 typedef log4kmw::Event<23> BootUp;
 typedef log4kmw::Event<26> CAN_APU_FAN1_Changed;
 typedef log4kmw::Event<27> CAN_APU_FAN2_Changed;
 typedef log4kmw::Event<25> CAN_BAG10_Changed;
 typedef log4kmw::Event<16> FGR_IO_CANStatus_Changed;
 typedef log4kmw::Event<17> FGR_IO_InternalError_Changed;
 typedef log4kmw::Event<18> FGR_PPC_CANStatus_Changed;
 typedef log4kmw::Event<19> FGR_PPC_InternalError_Changed;
 typedef log4kmw::Event<14> FGR_PWR_CANStatus_Changed;
 typedef log4kmw::Event<15> FGR_PWR_InternalError_Changed;
 typedef log4kmw::Event<12> FGR_VT_CANStatus_Changed;
 typedef log4kmw::Event<13> FGR_VT_InternalError_Changed;
 typedef log4kmw::Event<28> IFIS_Status_Changed;
 typedef log4kmw::Event<39> NAV_CAN_CommunicationChanged;
 typedef log4kmw::Event<40> NAV_StatusChanged;
 typedef log4kmw::Event<37> RFH_CAN_CommunicationChanged;
 typedef log4kmw::Event<38> RFH_DoorStatusChanged;
 typedef log4kmw::Event<36> RFH_Videosignal_Sync_Changed;
 typedef log4kmw::Event<30> Vehicle_HS_Changed;
 typedef log4kmw::Event<35> Vehicle_MainEngineRunning_Changed;
 typedef log4kmw::Event<33> Vehicle_Red_Warnings_Changed;
 typedef log4kmw::Event<34> Vehicle_Yellow_Warnings_Changed;
 typedef log4kmw::Event<32> Vehicle_high_Voltage;
 typedef log4kmw::Event<31> Vehicle_low_Voltage;
 typedef log4kmw::Event<24> ZLHV_CANStatus_Changed;
 typedef log4kmw::Event<22> ZM_Entry_Changed;
 typedef log4kmw::Event<29> ZM_UserInteractionSolved;
 typedef log4kmw::Event<20> ZWL_CANStatus_Changed;
 typedef log4kmw::Event<21> ZWL_InternalError_Changed;
}

#endif
